# Generated by Django 6.0.2 on 2026-02-17 04:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for Flutter app', max_length=50, null=True)),
                ('color', models.CharField(default='#000000', help_text='Hex color code for category', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(db_index=True, help_text='QR code or barcode value', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('brand', models.CharField(blank=True, help_text='Product brand', max_length=255, null=True)),
                ('category', models.CharField(blank=True, help_text='Product category (e.g., Dairy, Vegetables, Meat)', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Product image URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, help_text='Date when item was purchased')),
                ('expiry_date', models.DateField(help_text='Expiry date of the item')),
                ('location', models.CharField(blank=True, help_text='Storage location (e.g., Fridge, Pantry, Freezer)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the item', null=True)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired')], default='fresh', help_text='Current status based on expiry date', max_length=20)),
                ('notified', models.BooleanField(default=False, help_text='Whether user has been notified about expiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product reference', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='inventory.product')),
                ('user', models.ForeignKey(help_text='User who owns this item', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Inventory',
                'verbose_name_plural': 'User Inventories',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('low_stock', 'Low Stock')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.userinventory')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user', 'expiry_date'], name='inventory_u_user_id_363883_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['status'], name='inventory_u_status_4267f6_idx'),
        ),
    ]
